# Usar la imagen oficial de Tomcat 8.5 con JDK 8
FROM tomcat:8.5-jdk8

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /usr/local/tomcat/webapps/

# Copiar la carpeta del proyecto dentro del contenedor
COPY ./GestorDeProyectos /usr/local/tomcat/webapps/GestorDeProyectos/

# Listar el contenido del directorio del proyecto para depuración
# Esto solo es necesario temporalmente para verificar que la copia es exitosa
RUN ls -l /usr/local/tomcat/webapps/GestorDeProyectos/

# Copiar el conector de PostgreSQL y JSTL a la carpeta de librerías de Tomcat
COPY ./GestorDeProyectos/WEB-INF/lib/postgresql-42.7.2.jar /usr/local/tomcat/lib/
COPY ./GestorDeProyectos/WEB-INF/lib/jstl-1.2.jar /usr/local/tomcat/lib/

# Verificar que los archivos jar se hayan copiado correctamente (opcional)
RUN ls -l /usr/local/tomcat/lib/

# Exponer el puerto 8080 para que la aplicación esté disponible
EXPOSE 8080

# Comando para iniciar Tomcat
CMD ["catalina.sh", "run"]
